apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: svc-controle
spec:
  project: default
  source:
    repoURL: https://github.com/mgseixas91/gitops-k8s
    targetRevision: main
    path: environments/env6/apps/svc-controle/manifest
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
