#!/bin/bash
ENV=$1
GIT_REPO="https://github.com/mgseixas91/gitops-k8s.git"
TARGET_REV="main"

# Início do YAML do AppSet
cat <<EOF > /tmp/appset-$ENV.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-apps-$ENV
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: $ENV
  template:
    metadata:
      name: '{{env}}-{{app}}'
    spec:
      project: default
      source:
        repoURL: $GIT_REPO
        targetRevision: $TARGET_REV
        path: gitops-apps/apps/{{app}}/manifest
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
EOF

# Adiciona todos os apps dinamicamente
echo "  generators:" >> /tmp/appset-$ENV.yaml
echo "    - matrix:" >> /tmp/appset-$ENV.yaml
echo "        generators:" >> /tmp/appset-$ENV.yaml

# Ambiente generator
echo "          - list:" >> /tmp/appset-$ENV.yaml
echo "              elements:" >> /tmp/appset-$ENV.yaml
echo "                - env: $ENV" >> /tmp/appset-$ENV.yaml

# Apps generator
echo "          - list:" >> /tmp/appset-$ENV.yaml
echo "              elements:" >> /tmp/appset-$ENV.yaml

for APP in $(ls ../../gitops-apps/apps); do
  echo "                - app: $APP" >> /tmp/appset-$ENV.yaml
done

# Aplica o AppSet no ArgoCD
kubectl apply -n argocd -f /tmp/appset-$ENV.yaml

