apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-env6
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SEU_GITHUB/gitops-k8s.git
    path: environments/env6/apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
